project_id = "cdmcocfdakuligkjjoyn"

[functions.create-payment]
verify_jwt = false

[functions.check-batches]
verify_jwt = false

[functions.driver-batch]
verify_jwt = false

[functions.verify-payment]
verify_jwt = false

[functions.send-notification]
verify_jwt = false

[functions.guest-lookup]
verify_jwt = false

[functions.create-payment-intent]
verify_jwt = false
