// This file is auto-generated by Lovable. Do not modify it.

import { createLovableAuth } from "@lovable.dev/cloud-auth-js";
import { supabase } from "../supabase/client";

// Lazy initialize to avoid React hook issues at module load time
let lovableAuth: ReturnType<typeof createLovableAuth> | null = null;

const getLovableAuth = () => {
  if (!lovableAuth) {
    lovableAuth = createLovableAuth({});
  }
  return lovableAuth;
};

export const lovable = {
  auth: {
    signInWithOAuth: async (provider: "google" | "apple", opts?: { redirect_uri?: string }) => {
      const auth = getLovableAuth();
      const result = await auth.signInWithOAuth(provider, {
        ...opts,
      });

      if (result.redirected) {
        return result;
      }

      if (result.error) {
        return result;
      }

      try {
        await supabase.auth.setSession(result.tokens);
      } catch (e) {
        return { error: e instanceof Error ? e : new Error(String(e)) };
      }
      return result;
    },
  },
};
